spring:
  application:
    name: springboot-grpc-server

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23liS4x1Q75O4lXDwq
#            client-secret: 857f64a782c81a6ef48a83dca287589a06d48e9c
#            scope: user:email,read:user

  grpc:
    server:
      port: 9090
server:
  port: 8089



