spring:
  application:
    name: springboot-grpc-client
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Volumes/----Y/java_space/java-relation/springboot-grpc-client/src/main/resources/springDb.db
    username:
    password:
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
  logging:
    level:
      org.springframework.security: debug
      org.springframework.web.client: debug
server:
  port: 8088
grpc:
  client:
    localgrpcserver:
      address: static://localhost:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    aigcdetector-server:
#      address: "dns:///aigcdetectorservice.kycx:8088"
      address: static://10.10.192.57:31402
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
logging:
  level:
    org:
      hibernate:
        SQL: debug
