spring:
  application:
    name: springboot-grpc-client

server:
  port: 8088
grpc:
  client:
    localgrpcserver:
      address: static://localhost:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    aigcdetector-server:
#      address: "dns:///aigcdetectorservice.kycx:8088"
      address: static://10.10.192.57:31402
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext