spring:
  application:
    name: springboot-grpc-client
#  grpc:
#    client:
#      localgrpcserver:
#        address: static://localhost:9090
#        enableKeepAlive: true
#        keepAliveWithoutCalls: true
#        negotiationType: plaintext

server:
  port: 8088
grpc:
  client:
    localgrpcserver:
      address: static://localhost:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext