server:
  port: 8088
  servlet:
    context-path: /basic/
  tomcat:
    uri-encoding: utf-8
  error:
    whitelabel:
      enabled: false


spring:
  application:
    name: basic

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


sensitivity:
  user: wfcxAPI
  pwd: WuIi!*21
  url: http://apisafe.sticloud.cn
  basic: 'c2NpZW50aWZpYy1hZG1pbjpzY2llbnRpZmljLWFkbWluLXB3IyQjJUA'
  reviewExtent: '3'

swagger:
  enabled:true